-- Data siswa asli telah dihapus dari file ini untuk melindungi privasi.
-- Jangan commit data siswa asli ke repository.
-- Isi file ini dengan data dummy (contoh) jika diperlukan, misalnya:
--
-- INSERT INTO students (nis, name, class) VALUES
-- ('25019203', 'AGUNG WIBOWO', 'XI RPL 5');
